[features]
seeds = false
skip-lint = false
[programs.localnet]
solana_twitter = "42zpVFBSPbZdx5qZZJmsCREp1zNPKmgjpdjAmiNCtocV"

[registry]
url = "https://api.apr.dev"
# url = "https://anchor.projectserum.com"

[provider]
cluster = "Localnet"
wallet = "/home/karolsudol/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
